package com.ruanyun.web.model;
// Generated 2016-1-16 16:07:59 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TUserScoreInfo generated by hbm2java
 */
@Entity
@Table(name="t_user_score_info")
public class TUserScoreInfo  implements java.io.Serializable
{
	private static final long serialVersionUID = 1L;
	private Integer userScoreInfoId;
	 private String userScoreInfoNum;
	 private Float score;
	 private Integer scoreType;
	 private String scoreName;
	 private String userAppNum;
	 private Integer userType;
	 private Date scoreTime;
	 private String subCode;
	 private String subMsg;
	 private String orderId;
	 private String outBizNo;
	 private Integer status;

    public TUserScoreInfo() 
    {}
	
    public TUserScoreInfo(String userScoreInfoNum) 
    {
        this.userScoreInfoNum = userScoreInfoNum;
    }
    
    public TUserScoreInfo(String userScoreInfoNum, Float score, Integer scoreType, String scoreName,
    		String userAppNum, Integer userType, Date scoreTime, String subCode, String subMsg, String orderId, String outBizNo, Integer status) 
    {
       this.userScoreInfoNum = userScoreInfoNum;
       this.score = score;
       this.scoreType = scoreType;
       this.scoreName = scoreName;
       this.userAppNum = userAppNum;
       this.userType = userType;
       this.scoreTime = scoreTime;
       this.status = status;
       this.subCode = subCode;
       this. subMsg = subMsg;
       this. orderId = orderId;
       this. outBizNo = outBizNo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="user_score_info_id", unique=true, nullable=false)
    public Integer getUserScoreInfoId() {
        return this.userScoreInfoId;
    }
    
    public void setUserScoreInfoId(Integer userScoreInfoId) {
        this.userScoreInfoId = userScoreInfoId;
    }
    
    @Column(name="user_score_info_num", nullable=false, length=100)
    public String getUserScoreInfoNum() {
        return this.userScoreInfoNum;
    }
    
    public void setUserScoreInfoNum(String userScoreInfoNum) {
        this.userScoreInfoNum = userScoreInfoNum;
    }
    
    @Column(name="score", precision=12, scale=0)
    public Float getScore() {
        return this.score;
    }
    
    public void setScore(Float score) {
        this.score = score;
    }
    
    @Column(name="score_type")
    public Integer getScoreType()
    {
        return this.scoreType;
    }
    
    public void setScoreType(Integer scoreType) 
    {
        this.scoreType = scoreType;
    }
    
    @Column(name="score_name", length=200)
    public String getScoreName()
    {
        return this.scoreName;
    }
    
    public void setScoreName(String scoreName)
    {
        this.scoreName = scoreName;
    }
    
    @Column(name="user_app_num", length=100)
    public String getUserAppNum() {
        return this.userAppNum;
    }
    
    public void setUserAppNum(String userAppNum) 
    {
        this.userAppNum = userAppNum;
    }
    
    @Column(name="user_type")
    public Integer getUserType() 
    {
        return this.userType;
    }
    
    public void setUserType(Integer userType)
    {
        this.userType = userType;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="score_time", length=19)
    public Date getScoreTime() {
        return this.scoreTime;
    }
    
    public void setScoreTime(Date scoreTime) 
    {
        this.scoreTime = scoreTime;
    }
    
    @Column(name="sub_code")
    public String getSubCode() {
		return subCode;
	}

	public void setSubCode(String subCode) {
		this.subCode = subCode;
	}
	 @Column(name="sub_msg")
	public String getSubMsg() {
		return subMsg;
	}

	public void setSubMsg(String subMsg) {
		this.subMsg = subMsg;
	}

	 @Column(name="order_id")
	public String getOrderId() {
		return orderId;
	}

	public void setOrderId(String orderId) {
		this.orderId = orderId;
	}

	 @Column(name="out_biz_no")
	public String getOutBizNo() {
		return outBizNo;
	}

	public void setOutBizNo(String outBizNo) {
		this.outBizNo = outBizNo;
	}

	@Column(name="status")
	public Integer getStatus() {
		return status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}
}


